plugin.plugin_configuration.search_api_solr_connector.solr_cloud:
  type: plugin.plugin_configuration.search_api_solr_connector.standard
  label: 'Search API Solr standard connector settings for Solr cloud'
